#! /usr/bin/env python3
# -*- mode: Python;-*-
#
# Begin copyright
#
#  /home/jrf/Documents/books/Books20/Tools/python/journals
#
#   Part of the Books20 Project
#
#   Copyright 2018 James R. Fowler
#
#   All rights reserved. No part of this publication may be
#   reproduced, stored in a retrival system, or transmitted
#   in any form or by any means, electronic, mechanical,
#   photocopying, recording, or otherwise, without prior written
#   permission of the author.
#
#
# End copyright
#
'''
Journals entries from AAA/AJB
'''

import sys
import os
import configargparse as argp

from PyQt5 import QtWidgets
from PyQt5 import QtGui

import aabooks.journal.journalwindow as mw
import aabooks.journal.journal_rc
import aabooks.lib.utils as aautils
#
# Parse the command line arguments
#
def getargs():
    '''Get the command line arguments.'''
    
    parser = argp.ArgumentParser(description='Create or edit a journals.xml file',
                                 default_config_files=['~/.config/Books20/journals.conf'])

    aautils.standard_parser_args(parser)
    
    parser.add_argument('-i', '--input', type=str,
                        help='read the file INPUT for entries')

    parser.add_argument('-s', '--symbols', type=str,
                        help='use alternate symbol table,')


    args = parser.parse_known_args()[0]

    return args


#
# The main body
#

def main():
    '''Do something with the command line arguments and open the entry
    window.

    '''

    args = getargs()

    app = QtWidgets.QApplication(sys.argv)
    app.setApplicationName('Journal Search and Entry')
    app.setWindowIcon(QtGui.QIcon(':/icon_journals.svg'))

    form = mw.JournalWindow()
    app.focusChanged.connect(form.set_focus_changed)


    if args.version:
        form._help_about()
        sys.exit(0)

    if args.symbols is not None:
        form.set_symbol_table_name(args.symbols)


    if args.input is not None:
        fname = args.input
        if os.path.isfile(fname):
            form.open_file(fname)
            form.show_entry(1)
        else:
            # Should not access form.jf functions and indeed
            # this is broken right now.
            form._open_new_file()
            form._vardict['journal_file'].set_file_name(fname)
            form.set_window_title(form._vardict['journal_file'].get_base_name())
            form._new_entry()

    form.show()
    sys.exit(app.exec_())



main()
