#! /usr/bin/env python3
# -*- mode: Python;-*-

"""Journals entries from AAA/AJB
"""

import sys
import os
import argparse

from PyQt5.QtCore import *
from PyQt5.QtGui  import *
from PyQt5.QtWidgets import *

# Trouble shooting assistance
from pprint import *
pp = PrettyPrinter()

#import bookentry.journal_rc
import bookentry.journalWin as mw

__version__ = '1.0'

#
# Parse the command line arguments
#
def getargs():
   parser = argparse.ArgumentParser(description='Create or edit a journals.xml file')

   parser.add_argument('-V', '--version',
                       help='provide version info,',
                       action='store_true')
   parser.add_argument( '-i', '--input', type=str,
                        help='read the file INPUT for entries',
                        action='append')
   parser.add_argument( '-s', '--symbols', type=str,
                        help='use alternate symbol table,',
                        action='append')

   args = parser.parse_args()

   return args


#
# The main body
#

def main():

   args = getargs()

   app = QApplication(sys.argv)
   app.setApplicationName('Journal Entry')
   # app.setWindowIcon(QIcon(':/icon_journals.svg'))
   
   form = mw.JournalEntry()
   app.focusChanged.connect(form.setFocusChanged)

   if args.version:
      hstr = form.helpString()
      form.helpAbout()
      sys.exit(0)

   if args.symbols is not None:
      form.setSymbolTableName(args.symbols[0])

   if args.input is not None:
      fname = args.input[0]
      if os.path.isfile(fname):
         form.openFile(fname)
      else:
         form.openNewFile()
         form.jf.setFileName(fname)
         form.setWinTitle(form.jf.getBaseName())
      form.newEntry()

   form.show()
   sys.exit(app.exec_())



main()
