#! /usr/bin/env python3
# -*- mode: Python;-*-

"""Collection database main dialog to review and edit books entries
"""

import sys
import os
import argparse
from PyQt4.QtCore import *
from PyQt4.QtGui  import *

# Trouble shooting assistance
from pprint import *
pp = PrettyPrinter()

import collection.mainWindow as mw

__version__ = '1.0'

#
# Parse the command line aguments
#
def getargs():
   parser = argparse.ArgumentParser(description='Search and modify the my book Collection database.')

   parser.add_argument('-V', '--version',
                       help='provide version info,',
                       dest='version',
                       default=False,
                       action='store_true')
   parser.add_argument( '-d', '--database', type=str,
                        help='use the database input instead of Collections.db3',
                        dest='database',
                        default=None,
                        action='append')
   parser.add_argument( '-s', '--symbols', type=str,
                        help='use alternate symbol table,',
                        dest='symbols',
                        default=None,
                        action='append')

   args = parser.parse_args()

   return args
#
# The main body
#

def main():

   args = getargs()

   app = QApplication(sys.argv)
   app.setApplicationName('Book Collection')
   #app.setWindowIcon(QIcon(':/icon_ajb.svg'))
   
   form = mw.Collection()
   #QObject.connect(app, SIGNAL("focusChanged(QWidget *, QWidget *)"), 
   #                form.setFocusChanged)

   if args.version:
      hstr = form.helpString()
      form.helpAbout()
      sys.exit(0)

   if args.symbols is not None:
      #form.setSymbolTableName(args.symbols[0])
      pass


   # open database with input name otherwise
   # use the default database
   if args.database is not None:
      fname = args.database[0]
      if os.path.isfile(fname):
         if not form.setDatabaseName(fname):
            print('Could not open database', fname )
            sys.exit(1)
   else:
      fname = '/home/jrf/Documents/books/Collection/Collection.db3'
      if not form.setDatabaseName(fname):
         print('Could not open database', fname )
         sys.exit(1)
      

   form.show()
   sys.exit(app.exec_())



main()
