#! /usr/bin/env python3
# -*- mode: Python; -*-
# Begin copyright
#
#  /home/jrf/Documents/books/Books20/Tools/python/aabooks/lib/testheader
#  
#   Part of the Books20 Project
#
#   Copyright 2018 James R. Fowler
#
#   All rights reserved. No part of this publication may be
#   reproduced, stored in a retrieval system, or transmitted
#   in any form or by any means, electronic, mechanical,
#   photocopying, recording, or otherwise, without prior written
#   permission of the author.
#
#
# End copyright

from PyQt4.QtCore import *
from PyQt4.QtGui  import *

from ui_HeaderEntry import *

class HeaderEdit(QDialog, Ui_HeaderEdit):

    def __init__(self, parent=None):
        super(HeaderEdit, self).__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':

    import sys
    app = QApplication(sys.argv)
    app.setApplicationName('Book Entry')
    form = HeaderEdit()
    form.show()
    sys.exit(app.exec_())
   
    
