#! /usr/bin/env python3
# -*- mode: Python;-*-
#
# Begin copyright
#
#  /home/jrf/Documents/books/Books20/Tools/python/journals
#
#   Part of the Books20 Project
#
#   Copyright 2018 James R. Fowler
#
#   All rights reserved. No part of this publication may be
#   reproduced, stored in a retrival system, or transmitted
#   in any form or by any means, electronic, mechanical,
#   photocopying, recording, or otherwise, without prior written
#   permission of the author.
#
#
# End copyright
#
'''
Journals entries from AAA/AJB
'''

import sys
import os
import argparse

from PyQt5 import QtWidgets

import aabooks.journal.journalwindow as mw

#
# Parse the command line arguments
#
def getargs():
    '''Get the command line arguments.'''
    parser = argparse.ArgumentParser(description='Create or edit a journals.xml file')

    parser.add_argument('-V', '--version',
                        help='provide version info,',
                        action='store_true')

    parser.add_argument('-i', '--input', type=str,
                        help='read the file INPUT for entries')

    parser.add_argument('-s', '--symbols', type=str,
                        help='use alternate symbol table,')

    parser.add_argument('-c', '--config', type=str,
                        help='use alternate configuration file name,',
                        default='./journals.conf')

    args = parser.parse_args()

    return args


#
# The main body
#

def main():
    '''Do something with the command line arguments and
    open the entry window.
    '''

    args = getargs()

    app = QtWidgets.QApplication(sys.argv)
    app.setApplicationName('Journal Search and Entry')
    # app.setWindowIcon(QIcon(':/icon_journals.svg'))

    form = mw.JournalWindow(config_name=args.config)
    app.focusChanged.connect(form.set_focus_changed)


    if args.version:
        form.help_about()
        sys.exit(0)

    if args.symbols is not None:
        form.set_symbol_table_name(args.symbols)

    if args.input is not None:
        fname = args.input
        if os.path.isfile(fname):
            form.open_file(fname)
            form.show_entry(1)
        else:
            form.open_new_file()
            form.jf.setFileName(fname)
            form.set_window_title(form.jf.getBaseName())
            form.new_entry()

    form.show()
    sys.exit(app.exec_())



main()
