#! /usr/bin/env python3
# -*- coding: utf-8 -*-
'''This list is used for testing search.py.'''

titleList =  [
 ("Astronomische Abhandlungen", 1),
 ("Ergänzungshefte zu den Astronomischen Nachrichten", 1),
 ("Abhandlungen der Preußischen Akademie der Wissenschaften", 1),
 ("Mathematische und naturwissenschaftliche Klasse", 1),
 ("Annalen der Hydrographie und maritimen Meteorologie", 1),
 ("Annales Françaises de Chronométrie", 1),
 ("Annales d'Astrophysique", 1),
 ("publiées par le service de recherche d'astrophysique de la caisse nationale de la recherche scientifique", 1),
 ("Annales de physique", 1),
 ("Archives des sciences physiques et naturalles", 1),
 ("Archiv der Deutschen Seewarte", 1),
 ("Archives du Musée Teyler", 1),
 ("Arkiv för Matematik, Astronomi och Fysik", 1),
 ("l'Astronomie", 1),
 ("Bulletin de la Société Astronomique de France", 1),
 ("Popular Astronomy", 1),
 ("Gerlands Beiträge zur Geophysik", 1),
 ("Beobachtungszirkulare der Astronomischen Nachrichten", 1),
 ("Berichte über die Verhandlungen der Sächsichen Akademie der Wissenschaften zu Leipzig", 1),
 ("Physikalische Berichte", 1),
 ("Bibliographie Mensuelle de l'Astronomie", 1),
 ("Bibliographie Géodésique Internationale", 1),
 ("Astronomische Blätter", 1),
 ("Zeitschrift der Astronomischen Abteilung des Königlich Ungarischen Naturwissenschaftlichen Vereins", 1),
 ("Bulletin of the Astronomical Institues of the Netherlands", 1),
 ("Bulletin de l'Association Française d'Observateurs d'Etoiles Variable", 1),
 ("Bulletin Astronomique", 1),
 ("Bulletin horaire", 1),
 ("Ciet et Terre", 1),
 ("Bulletin mensuel de la Sociéte Belge d'Astronomie, de Météorologie et de Physique de Globe", 1),
 ("Coelum", 1),
 ("Comptes Rendus", 1),
 ("hebdomadaires des Séances de l'Académie des Sciences", 1),
 ("Comptes Rendus de l'Académie des Sciences de l'Union des USSR", 1),
 ("Contributions of the Society for Research on Meteorites", 1),
 ("Eudemus", 1),
 ("An International Journal devoted to the history of mathematics and astronomy", 1),
 ("Forschungen und Fortschritte", 1),
 ("Nachrichtenblatt der Deutschen Wissenschaft un Tecknik", 1),
 ("Hemel en Dampkring", 1),
 ("Astronomical Herald", 1),
 ("Die Himmelswelt", 1),
 ("Hochfrequenztechnik und Elektroakustik", 1),
 ("Jahrbuch der drahtlosen Telegraphie und Telephonie", 1),
 ("The Astronomical Journal", 1),
 ("The Astrophysical Journal", 1),
 ("Journal of the British Astronomical Association", 1),
 ("Journal des Observateurs", 1),
 ("Journal of the Washington Academy of Sciences", 1),
 ("Astronomical Journal of Soviet Union", 1),
 ("Journal of Calendar Reform", 1),
 ("Journal of the Optical Society of America", 1),
 ("Journal of the Franklin Institute", 1),
 ("Japanese Journal of Astronomy and Geophysics", 1),
 ("Journal of the Royal Astronomical Society of Canada", 1),
 ("Csillagászati Lapok", 1),
 ("The London, Edinburgh and Dublin Philosophical Magazine and Journal of Science", 1),
 ("Memoirs of the British Astronomical Association", 1),
 ("Memoirs of the Royal Astronomical Society", 1),
 ("Memorie della Societá Astronomica Italiana", 1),
 ("Nuova Serie", 1),
 ("Mitteilungen und Beobachtungen der Tschechischen Astronomischen Gesellschaft in Prag", 1),
 ("Astronomische Nachrichten", 1),
 ("Nachrichten der Akademie der Wissenschaften zu Göttingen", 1),
 ("Math.-Phys. Klasse", 1),
 ("Zeiss Nachrichten", 1),
 ("Nature", 1),
 ("Die Naturwissenschaften", 1),
 ("Occasional Notes", 1),
 ("Royal Astronomical Society", 1),
 ("Monthly Notices of the Royal Astronomical Society", 1),
 ("Monthly Notices of the Royal Astronomical Society", 1),
 ("Geophysical Supplement", 1),
 ("The Observatory", 1),
 ("Proceedings of the Section of Science", 1),
 ("Koninklijke Akademie van Wetenschappen te Amsterdam", 1),
 ("Proceedings of the Royal Society", 1),
 ("Series A", 1),
 ("Mathematical and Physical Science", 1),
 ("Proceedings of the American Philosophical Society", 1),
 ("Proceedings of the Imperial Academy", 1),
 ("Proceedings of the Physico-Mathematical Society of Japan", 1),
 ("Proceedings of the National Academy of Sciences of the United States of America", 1),
 ("Publications of the American Astronomical Society", 1),
 ("Publications of the Astronomical Society of the Pacific", 1),
 ("The Physical Review", 1),
 ("The Review of Scientific Instruments", 1),
 ("Revue d'Optique théorique et instrumentale", 1),
 ("Rise hvezd", 1),
 ("Science", 1),
 ("A Weekly Journal devoted to the Advancement of Science", 1),
 ("Scientia", 1),
 ("Revue de synthèse scientifique", 1),
 ("Sitzungsberichte der mathematische-physikalischen Klasse der Bayerischen Akademie der Wissenschaften zu München", 1),
 ("Sitzungsberichte der Akademie der Wissenschaft in Wien", 1),
 ("Mathematisch-naturwissenschaftliche Klasse", 1),
 ("Abteilung IIa Mathematik, Astronomie, Physik, Meteorologie und Technik", 1),
 ("The Sky", 1),
 ("Magazine of Cosmic News", 1),
 ("Der Sterne", 1),
 ("The Telescope", 1),
 ("Terrestrial Magnetism and Atmospheric Electricity", 1),
 ("Nordisk Astronomisck Tidsskrift", 1),
 ("Populär Astronomisk Tidskrift", 1),
 ("Philosophical Transactions of the Royal Society of London", 1),
 ("Series A, Mathematical and Physical Sciences", 1),
 ("Vierteljahrsschrift der Astronomischen Gesellschaft", 1),
 ("Weltall", 1),
 ("Weltraum", 1),
 ("Mitteilungsblatt der Gesellschaft für Weltraumforschung", 1),
 ("Zeitschrift für Astrophysik", 1),
 ("Zeitshrift für Instrumentenkunde", 1),
 ("Zeitschrift für physikalischen und chemischen Unterricht", 1),
 ("Zeitschrift für die gesamte Naturwissenschaft", 1),
 ("Zeitschrift für Geophysik", 1),
 ("Zeitschrift für Physik", 1),
 ("Physikalische Zeitscrift", 1),
 ("Zentralblatt für Geophysik, Meteorolgie und Geodäsie", 1),
 ("Zentralblatt für Mathematik und ihre Grenzgebiete", 1),
 ("Literarisches Zentralblatt", 1),
 ("Ann d Hydrog", 1),
 ("Ann d'Astrophys", 1),
 ("Ark Mat Astr Fys", 1),
 ("BSAF", 1),
 ("Pop Astr", 1),
 ("BZ", 1),
 ("Phys Ber", 1),
 ("BMA", 1),
 ("BAN", 1),
 ("BAF", 1),
 ("Bull hor", 1),
 ("CR", 1),
 ("AJ", 1),
 ("ApJ", 1),
 ("JBAA", 1),
 ("JO", 1),
 ("J Opt Soc Amer", 1),
 ("JCan RAS", 1),
 ("J Can RAS", 1),
 ("Mem BAA", 1),
 ("Mem RAS", 1),
 ("Mem SA It", 1),
 ("Mem SA It NS", 1),
 ("AN", 1),
 ("Nat", 1),
 ("MN", 1),
 ("MN RAS", 1),
 ("MN Geophys Suppl", 1),
 ("Obs", 1),
 ("Tok Proc", 1),
 ("Proc NAS", 1),
 ("Publ AAS", 1),
 ("PASP", 1),
 ("Publ ASP", 1),
 ("Phys Rev", 1),
 ("Rev Scient Inst", 1),
 ("Rev Sci Inst", 1),
 ("Rev d'Opt Théor et Instr", 1),
 ("RH", 1),
 ("Sterne", 1),
 ("NAT", 1),
 ("PAT", 1),
 ("Phil Trans", 1),
 ("VJS", 1),
 ("ZfA", 1),
 ("ZfInstrk", 1),
 ("ZfPhys", 1),
 ("Phys Z", 1),
 ("ZfGMG", 1)]

colorList = [
    ('red', ('apple', 'blood', 'cherry', 'ferrari')),
    ('reddish', ('blood', 'apple', 'ferrari')),
    ('orange', ('orange', 'blanket')),
    ('pink', ('fish', 'dress', 'candy')),
    ('black', ('licorice', 'night', 'bear', 'dress')),
    ('blue', ('sky', 'ocean', 'fish', 'dress'))
]


if __name__ == '__main__':
    print('No tests available.  This is a list of title for testing search.py')
